[package]
name = "ayeneh-tui"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "ayeneh-tui"
path = "src/main.rs"

[dependencies]
ayeneh-cli = { path = "../cli" }
ayeneh-core = { path = "../core" }
ratatui = { workspace = true }
crossterm = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }